# Config for DDS converter
# Ver: 2.2

# Directory where the files that needed to be converted are stored. Default: "DDS"
input_dir: DDS

# Directory where files that was converted will be stored. Default: "PNG"
output_dir: PNG

# File format of files that needed to be converted
input_file_format: .dds

# File format of files that will be converted
output_file_format: .png